<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\Department.cs~RF1fa88a73.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Enums\" />
  </ItemGroup>

</Project>
